management:
  endpoints:
    web:
      exposure:
        # https://docs.spring.io/spring-boot/docs/3.1.5/actuator-api/htmlsingle/#overview
        include: health,metrics

springdoc:
  api-docs:
    path: /api-docs
